language: node_js
node_js:
  - 4
  - 6
  - 7.6

cache:
  directories:
    - $HOME/.pnpm-store

sudo: false
before_install:
  - npm install -g @zkochan/pnpm@0.62.4
install:
  - pnpm install
script:
  - npm test
env:
  global:
    - CC=clang CXX=clang++ npm_config_clang=1
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: pnpm/pnpm
